apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
  - name: multitool-container
    image: wbitt/network-multitool:latest
    command:
      - sh
      - -c
      - "echo The multitool is running! && sleep 3600"
    ports:
      - containerPort: 8080
